# version: '3.8'

# services:
#   backend:
#     build: .
#     container_name: p2p-backend
#     ports:
#       - "5000:5000"
#     environment:
#       - NODE_ENV=production
#       - MONGO_URI=mongodb://mongo:27017/p2p-marketplace
#     depends_on:
#       mongo:
#         condition: service_healthy
#     restart: unless-stopped
#     networks:
#       - p2p-network

#   mongo:
#     image: mongo:6
#     container_name: p2p-mongo
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example
#     volumes:
#       - mongo-data:/data/db
#     healthcheck:
#       test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
#       interval: 30s
#       timeout: 10s
#       retries: 5
#       start_period: 40s
#     networks:
#       - p2p-network
#   redis:
#     image: redis:7-alpine
#     container_name: p2p-redis
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data
#     healthcheck:
#       test: ["CMD", "redis-cli", "ping"]
#       interval: 30s
#       timeout: 10s
#       retries: 3

# volumes:
#   redis_data:
# volumes:
#   mongo-data:
#   redis-data:

# networks:
#   p2p-network:
#     driver: bridge